version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: govis
    main: ./cmd/govis
    binary: govis
    ldflags:
      - -s -w -X github.com/thzgajendra/govis.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: govis
    builds:
      - govis
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "govis_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: thzgajendra
    name: govis
  prerelease: auto
