package render

import (
	"fmt"
	"io"
	"sort"
	"strings"

	reqflow "github.com/thzgajendra/reqflow"
)

type MarkdownRenderer struct{}

func (m *MarkdownRenderer) Render(g *reqflow.Graph, w io.Writer) error {
	fmt.Fprintln(w, "# 📐 Architecture Documentation")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "> Auto-generated by [Reqflow](https://github.com/thzgajendra/reqflow)")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "")

	// Group nodes by package
	pkgNodes := make(map[string][]*reqflow.Node)
	for _, n := range g.Nodes {
		pkgNodes[n.Package] = append(pkgNodes[n.Package], n)
	}

	// Sort package names for deterministic output
	var pkgNames []string
	for pkg := range pkgNodes {
		pkgNames = append(pkgNames, pkg)
	}
	sort.Strings(pkgNames)

	// ---- Package-by-package documentation ----
	for _, pkg := range pkgNames {
		nodes := pkgNodes[pkg]
		sort.Slice(nodes, func(i, j int) bool {
			return kindPriority(nodes[i].Kind) < kindPriority(nodes[j].Kind)
		})

		fmt.Fprintf(w, "## 📦 Package: `%s`\n\n", pkg)

		for _, n := range nodes {
			icon := kindIcon(n.Kind)
			fmt.Fprintf(w, "### %s %s\n", icon, n.Name)
			fmt.Fprintf(w, "- **Type:** `%s`\n", n.Kind)

			if n.File != "" {
				fmt.Fprintf(w, "- **Location:** `%s:%d`\n", n.File, n.Line)
			}

			if route, ok := n.Meta["route"]; ok {
				fmt.Fprintf(w, "- **API Route:** `%s`\n", route)
			}

			if ks, ok := n.Meta["vitess_keyspace"]; ok {
				shardInfo := "Unsharded"
				if n.Meta["vitess_sharded"] == "true" {
					shardInfo = "Sharded"
				}
				fmt.Fprintf(w, "- **Vitess:** Keyspace `%s` (%s)\n", ks, shardInfo)
			}

			if embed, ok := n.Meta["grpc_embed"]; ok {
				fmt.Fprintf(w, "- **gRPC Embed:** `%s`\n", embed)
			}

			if len(n.Methods) > 0 {
				fmt.Fprintln(w, "- **Methods:**")
				for _, method := range n.Methods {
					fmt.Fprintf(w, "  - `%s()`\n", method)
				}
			}

			if len(n.Fields) > 0 {
				fmt.Fprintln(w, "- **Fields:**")
				for _, f := range n.Fields {
					fmt.Fprintf(w, "  - `%s` → `%s`\n", f.Name, f.Type)
				}
			}

			// Find dependencies
			var deps []string
			for _, e := range g.Edges {
				if e.From == n.ID {
					if target, ok := g.Nodes[e.To]; ok {
						deps = append(deps, fmt.Sprintf("`%s` (%s)", target.Name, e.Kind))
					}
				}
			}
			if len(deps) > 0 {
				fmt.Fprintln(w, "- **Dependencies:**")
				for _, d := range deps {
					fmt.Fprintf(w, "  - → %s\n", d)
				}
			}

			fmt.Fprintln(w, "")
		}

		fmt.Fprintln(w, "---")
		fmt.Fprintln(w, "")
	}

	// ---- Summary Statistics ----
	metrics := reqflow.ComputeMetrics(g)
	fmt.Fprintln(w, "## 📊 Coupling Metrics")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "| Component | Kind | Fan-In | Fan-Out | Methods | Risk |")
	fmt.Fprintln(w, "|-----------|------|--------|---------|---------|------|")

	for _, m := range metrics {
		risk := "✅ Low"
		total := m.FanIn + m.FanOut
		if total > 10 {
			risk = "🔴 God Object"
		} else if total > 5 {
			risk = "🟡 Watch"
		}
		fmt.Fprintf(w, "| %s | %s | %d | %d | %d | %s |\n",
			m.Name, m.Kind, m.FanIn, m.FanOut, m.Methods, risk)
	}
	fmt.Fprintln(w, "")

	// ---- Cycle warnings ----
	cycles := reqflow.DetectCycles(g)
	if len(cycles) > 0 {
		fmt.Fprintln(w, "## ⚠️ Circular Dependencies Detected")
		fmt.Fprintln(w, "")
		for i, cycle := range cycles {
			var names []string
			for _, id := range cycle {
				if n, ok := g.Nodes[id]; ok {
					names = append(names, n.Name)
				} else {
					names = append(names, id)
				}
			}
			fmt.Fprintf(w, "%d. `%s`\n", i+1, strings.Join(names, " → "))
		}
		fmt.Fprintln(w, "")
	}

	return nil
}

func kindIcon(k reqflow.NodeKind) string {
	switch k {
	case reqflow.KindHandler:
		return "🌐"
	case reqflow.KindService:
		return "⚙️"
	case reqflow.KindStore:
		return "🗄️"
	case reqflow.KindModel:
		return "📋"
	case reqflow.KindEvent:
		return "📢"
	case reqflow.KindMiddleware:
		return "🛡️"
	case reqflow.KindGRPC:
		return "⚡"
	case reqflow.KindInfra:
		return "☁️"
	case reqflow.KindInterface:
		return "🔌"
	default:
		return "📦"
	}
}

func kindPriority(k reqflow.NodeKind) int {
	switch k {
	case reqflow.KindHandler:
		return 0
	case reqflow.KindMiddleware:
		return 1
	case reqflow.KindGRPC:
		return 2
	case reqflow.KindService:
		return 3
	case reqflow.KindStore:
		return 4
	case reqflow.KindModel:
		return 5
	case reqflow.KindEvent:
		return 6
	case reqflow.KindInfra:
		return 7
	default:
		return 10
	}
}
